'use strict';

var libs = ['bootstrap-notify', 'bootstrap', 'vue', 'bootbox', 'lodash', 'vuex', 'vue-resource', 'vue-router', 'jquery', 'xterm', 'reconnectingwebsocket', 'md5', 'moment', 'xterm', 'vue2-ace-editor', 'liquor-tree', 'blockly/blockly_compressed.js', 'blockly/blocks_compressed_wyliolab.js', 'blockly/msg/js/en_wyliolab.js', 'blockly/python_compressed_wyliolab.js'];

var fs = require ('fs');
var path = require ('path');

module.exports = function(grunt) {
	var tasks = {
		browserify: {
			ui: {
				files: {
					'build/ui/js/login.js': ['src/ui/js/login.js'],
					'build/ui/js/lab.js': ['src/ui/js/lab.js'],
					'build/ui/js/admin.js': ['src/ui/js/admin.js'],
				},
				options: {
					transform: ['vueify']
				}
			},
			docs: {
				files: {
					'build/docs/js/script.js': ['src/docs/js/script.js'],
				},
				options: {
					external: null
				}
			},
			vendor: {
				src: [],
				dest: 'build/ui/js/vendor.js',
				options: {
					external: null,
					require: libs,
				},
			},
			freeboard: {
				files: {
					'build/ui/js/freeboard/wyliodrinData.js': 'src/ui/js/freeboard/wyliodrinData.js'
				},
				options: {
					external: null
				}
			},
			options: {
				external: libs,
			},
		},

		copy: {
			server: {
				files: [{
					expand: true,
					cwd: 'src/server',
					src: ['**/*'],
					dest: 'build/server/'
				},
				// {
				// 	expand: true,
				// 	cwd: 'src/server/bin',
				// 	src: ['*'],
				// 	dest: 'build/server/bin/'
				// },
				// {
				// 	expand: true,
				// 	cwd: 'src/server/database',
				// 	src: ['*'],
				// 	dest: 'build/server/database/'
				// },
				// {
				// 	expand: true,
				// 	cwd: 'src/server/routes',
				// 	src: ['*'],
				// 	dest: 'build/server/routes/'
				// }
				]
			},
			ui: {
				files: [{
					expand: true,
					cwd: 'src/ui/img',
					src: ['**/*'],
					dest: 'build/ui/img/'
				},
				{
					expand: true,
					cwd: 'src/ui',
					src: ['**/*.html'],
					dest: 'build/ui'
				},
				{
					expand: true,
					cwd: 'src/ui/freeboard',
					src: ['**/*'],
					dest: 'build/ui/freeboard',
					extDot: 'first'
				},
				{
					expand: true,
					cwd: 'src/ui/fonts',
					src: ['**/*'],
					dest: 'build/ui/fonts/'
				},
				]
			},

			docs: {
				files: [{
					expand: true,
					cwd: 'src/docs/',
					src: ['**/*', '!**/*.js'],
					dest: 'build/docs/',
					extDot: 'first'
				}, ]
			}
		},
		//clean the build folder
		clean: {
			all: 'build',
			client: 'build/client',
			server: 'build/server',
			docs: 'build/docs'
		},
		less: {
			docs: {
				files: {
					'build/docs/css/docs.css': 'src/docs/css/docs.less'
				}
			},
			vendor: {
				files: {
					'build/ui/style/wyliodrin.css': 'src/ui/style/style.less',
					'build/ui/style/studio.css': 'src/ui/style/studio.less',
					// 'build/ui/style/admin.css': 'src/ui/style/admin.less',
					'build/ui/style/vendor.css': 'src/ui/style/vendor.less'
				}
			}
		},
		eslint: {
			gruntfile: 'Gruntfile.js',
			server: ['src/server/**/*.js', '!src/server/server-tftp/**/*.js'],
			ui: ['src/ui/**/*.js', 'src/ui/**/*.vue', '!src/ui/freeboard/**/*', '!src/ui/js/blockly/**/*']
		}
	};

	grunt.registerTask ('blockly', 'Blockly', function (label)
	{
		let blockly_compressed = fs.readFileSync ('node_modules/blockly/blockly_compressed.js').toString ();
		blockly_compressed += '\nmodule.exports = {\n\tBlockly,\n\tgoog\n};';
		fs.writeFileSync ('node_modules/blockly/blockly_compressed_wyliolab.js', blockly_compressed);

		function wrap (filename)
		{
			let extension = path.extname (filename);
			let filename_wyliolab = filename.substring (0, filename.length-extension.length)+'_wyliolab'+extension;
			// console.log (filename_wyliolab);
			let data = fs.readFileSync (filename).toString ();
			data = '// DO NOT EDIT THIS FILE, IT IS AUTMATICALLY GENERATED\n\nmodule.exports = function (blockly) {\n\tvar Blockly = blockly.Blockly;\n\tvar goog = blockly.goog;\n' + data +'\n};';
			fs.writeFileSync (filename_wyliolab, data);
		}

		if (!label || label === 'ui')
		{
			wrap ('node_modules/blockly/blocks_compressed.js');
			wrap ('node_modules/blockly/msg/js/en.js');
			wrap ('node_modules/blockly/python_compressed.js');
		}
		if (!label || label === 'blocks')
		{
			wrap ('src/ui/js/blockly/definitions.js');
			wrap ('src/ui/js/blockly/code.js');
		}
	});

	grunt.initConfig(tasks);
	grunt.loadNpmTasks('grunt-browserify');
	grunt.loadNpmTasks('grunt-contrib-less');
	grunt.loadNpmTasks('grunt-contrib-copy');
	grunt.loadNpmTasks('grunt-contrib-clean');
	grunt.loadNpmTasks('grunt-eslint');

	grunt.registerTask('server', ['eslint:server', 'copy:server']);

	grunt.registerTask('ui', ['eslint:ui', 'blockly', 'browserify', 'less', 'copy:ui']);

	grunt.registerTask('docs', ['browserify:docs', 'copy:docs', 'less:docs']);
	grunt.registerTask('fastui', ['eslint:ui', 'blockly:blocks', 'browserify:ui', 'browserify:freeboard']);

	grunt.registerTask('default', ['server', 'ui', 'docs']);
};